
spring:
  profiles:
    active: dev
  datasource:
    initialization-mode: ALWAYS
    schema: classpath:acl-schema.sql
    data: classpath:acl-data.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
