spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example_spring_security_acl?createDatabaseIfNotExist=true
    password: 123456
    username: admin
    driver-class-name: com.mysql.jdbc.Driver
