#redis配置地址
spring:
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://uaa:8090/uaa/token_keys

# actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

# 端口
server:
  port: 9000

logging:
  level:
    root: info
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: debug
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug
